global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8081']
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-management-service:8082']
  - job_name: 'offer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['offer-management-service:8083']
  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reservation-transaction-service:8084']
  - job_name: 'file-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['file-service:8085']
  - job_name: 'favorite-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['favorite-service:8086']
  - job_name: 'reporting-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reporting-safety-service:8087']